// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Vortex.Infrastructure.Datos;

#nullable disable

namespace Vortex.Infrastructure.Datos.Migraciones.Sqlite
{
    [DbContext(typeof(VortexDbContextSqlite))]
    partial class VortexDbContextSqliteModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("Vortex.Domain.Catalogo.Producto", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Codigo")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Descripcion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Precio")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<bool>("PrecioIncluyeIgv")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Unidad")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Productos", (string)null);
                });

            modelBuilder.Entity("Vortex.Domain.Configuracion.Negocio", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CondicionesPredeterminadas")
                        .HasColumnType("TEXT");

                    b.Property<string>("Direccion")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreComercial")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("RazonSocial")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Regimen")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Ruc")
                        .HasMaxLength(11)
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefono")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("Ubigeo")
                        .HasMaxLength(6)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Negocio", (string)null);
                });

            modelBuilder.Entity("Vortex.Domain.Contactos.Contacto", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Cargo")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Dni")
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("EmpresaId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefono")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.ToTable("Contactos", (string)null);
                });

            modelBuilder.Entity("Vortex.Domain.Contactos.Empresa", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("CondicionSunat")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Direccion")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("EstadoSunat")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreComercial")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("RazonSocial")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Ruc")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefono")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("Ubigeo")
                        .HasMaxLength(6)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Ruc");

                    b.ToTable("Empresas", (string)null);
                });

            modelBuilder.Entity("Vortex.Domain.Tareas.Tarea", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int?>("AvisarMinutosAntes")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("CompletadaEn")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ContactoId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("EmpresaId")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<TimeOnly?>("Hora")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notas")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("OportunidadId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ContactoId");

                    b.HasIndex("EmpresaId");

                    b.HasIndex("OportunidadId");

                    b.ToTable("Tareas", (string)null);
                });

            modelBuilder.Entity("Vortex.Domain.Ventas.Cotizacion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Condiciones")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ContactoId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("EmpresaId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("FechaEmision")
                        .HasColumnType("TEXT");

                    b.Property<string>("Lineas")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ModoIgv")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("Numero")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("OportunidadId")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("ValidaHasta")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ContactoId");

                    b.HasIndex("EmpresaId");

                    b.HasIndex("Numero")
                        .IsUnique();

                    b.HasIndex("OportunidadId");

                    b.ToTable("Cotizaciones", (string)null);
                });

            modelBuilder.Entity("Vortex.Domain.Ventas.Oportunidad", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("CerradoEn")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ContactoId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("EmpresaId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Etapa")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("FechaCierreEstimada")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Monto")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<string>("MotivoPerdida")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notas")
                        .HasColumnType("TEXT");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ContactoId");

                    b.HasIndex("EmpresaId");

                    b.ToTable("Oportunidades", (string)null);
                });

            modelBuilder.Entity("Vortex.Domain.Configuracion.Negocio", b =>
                {
                    b.OwnsMany("Vortex.Domain.Configuracion.Sucursal", "Sucursales", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("TEXT");

                            b1.Property<bool>("Activa")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("CodigoEstablecimiento")
                                .IsRequired()
                                .HasMaxLength(4)
                                .HasColumnType("TEXT");

                            b1.Property<string>("Direccion")
                                .HasMaxLength(300)
                                .HasColumnType("TEXT");

                            b1.Property<int>("NegocioId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Nombre")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("TEXT");

                            b1.Property<string>("Ubigeo")
                                .HasMaxLength(6)
                                .HasColumnType("TEXT");

                            b1.HasKey("Id");

                            b1.HasIndex("NegocioId");

                            b1.ToTable("Sucursales", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("NegocioId");
                        });

                    b.Navigation("Sucursales");
                });
#pragma warning restore 612, 618
        }
    }
}
